"""
Django settings for APPRoot project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import datetime
import os
import pymysql

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5eel2pz171_-i^l*c8xnew9n97na7xkccbvm5%%^wz0daaft%z'
PRIVATE_KEY = """
MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALI5hWq+zx021uJ3
U+xHlnzLICwq7YvmlOL/igo6phwjL+ygSJUo1PiWZrYgP3g9abs5WWF/lfqSIP0W
ASQ3GM7Cn+EVdLo+owVHl0zPVSL7G4NlkxEdO0LMrkksPlBKE2eSBPnHgZzOHiB2
pogfWM4TAaLLoz6DSOe3l5+f1yUZAgMBAAECgYBmQyMOkNV+Sc0avKVm2dy7VkHr
leYfc/rSFRY7sFNHqdkBySZcj8VDrejZb797WqGkT8+9ZdvEnrxW+51EDmkopNuE
16yTc5iljIcYHvq1vidzCMBxCN9ZaSETy3ygmCZxmaDfaWqLWMbRi8EBCWhfFrch
sr/La/I6LOCo8xHiUQJBANZBzrBGElCHUchufU2cj07Uw7zQB69QKCY7OMpvTusH
1TpviIgdn6gnL42AxmtelHkDjr5Lwq9mDOw7HgEJ/d8CQQDU8pQ2K/BWKGIRTfoH
FHMnMIwVAl1D3vGHJNmP2oYJPxTAaCZfpWuMSNYm+NjcPiLXruMozsu5wqAy9OEf
LUwHAkEAiKegdL28oLAucXBHa2EX5me+EId+30p40SmkpzknVLDCR2sr4eVDF7Um
l1IzO/gvKqAiQy1/FvA3/dQW5wLAcQJAVQiQ+pjNHfp+Pp6+qrkVyp5uMa2CBKow
FGE4p2MBhwuzg6mTOTpbGeez7FgOcNQ3IZ1qhE8ftwvq4K48fzCdXQJAWbeg/pHR
OQIDK5LcXrlY2B2/0IGkpI0K3dzLt3Dwio9lZt8U/dUVo8fhF7RK8nkDAXHdqM4t
QBGWJiywOVj7uQ==
"""
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loveword',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken'
]
CORS_ORIGIN_ALLOW_ALL = True  # 新增的跨域访问设置

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'APPRoot.urls'
# APPEND_SLASH这个常量默认为True，就是假如你没有添加斜线，他会帮你添加上(总体是这样，具体得看源码怎么写的了)
APPEND_SLASH = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'APPRoot.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 数据库引擎（是mysql还是oracle等）
        # 'ENGINE': 'django.db.backends.mysql',
        # # 数据库的名字
        # 'NAME': 'mdm',
        # # 连接mysql数据库的用户名
        # 'USER': 'kl',
        # # 连接mysql数据库的密码
        # 'PASSWORD': 'shcl',
        # # mysql数据库的主机地址
        # 'HOST': '192.168.5.61',
        # # mysql数据库的端口号
        # 'PORT': '3306',

    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    # 主项目的公共静态文件
    os.path.join(BASE_DIR, 'APPRoot', 'static'),
    # APP模块的私有静态文件
    os.path.join(BASE_DIR, 'loveword', 'static')
]

TOKEN_LIFETIME = 7
# REST_FRAMEWORK配置文件

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',  # 未认证用户一分钟只许访问100次        
        'user': '60/minute',  # 认证用户一分钟可以访问1000次
        'limit': '100/minute'
    },
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    #     'rest_framework.authentication.SessionAuthentication',
    # ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    # 异常处理 ： https://www.cnblogs.com/crazymagic/articles/10023528.html
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler',  # 这是使用自定制异常处理
}
