# Generated by Django 2.2.1 on 2020-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0004_nmsl'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmsl',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='嘴臭时间'),
        ),
    ]
