# Generated by Django 2.2.1 on 2020-08-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0008_comic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='作者名')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('location', models.CharField(max_length=50, verbose_name='分类')),
                ('copyright', models.CharField(max_length=5, verbose_name='版权')),
                ('state', models.CharField(max_length=5, verbose_name='状态')),
                ('content', models.TextField(verbose_name='简介')),
                ('uid', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='loveword.Comic', verbose_name='作品id')),
            ],
        ),
    ]
