# Generated by Django 2.2.1 on 2020-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0012_auto_20200824_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic_author',
            name='id',
        ),
        migrations.AlterField(
            model_name='comic_author',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='漫画作品ID'),
        ),
    ]
