# Generated by Django 2.2.1 on 2020-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0016_auto_20200826_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=10, verbose_name='视频作品ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('pic', models.CharField(max_length=200, verbose_name='封面')),
                ('judge', models.FloatField(verbose_name='评分')),
                ('quality', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='画质')),
                ('update', models.CharField(max_length=50, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='AVideo_chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=10, verbose_name='视频作品ID')),
                ('images_url', models.TextField(verbose_name='图片url')),
            ],
        ),
    ]
