# Generated by Django 2.2.1 on 2020-09-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0018_auto_20200904_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='留言ip地址')),
                ('uid', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户id')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户地址')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='邮箱')),
                ('contents', models.CharField(blank=True, max_length=240, null=True, verbose_name='留言内容')),
                ('reply', models.CharField(blank=True, max_length=240, null=True, verbose_name='回复')),
                ('update', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
