# Generated by Django 3.0 on 2020-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0019_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilibili',
            fields=[
                ('bvid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='bv号')),
                ('comment', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('created', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
                ('pic', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片地址')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('length', models.CharField(blank=True, max_length=10, null=True, verbose_name='视频长度')),
                ('play', models.IntegerField(blank=True, default=0, null=True, verbose_name='播放量')),
                ('ts', models.IntegerField(blank=True, null=True, verbose_name='时间戳')),
            ],
        ),
    ]
