# Generated by Django 2.2.1 on 2021-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0022_auto_20210217_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='content',
            field=models.CharField(default='社会经典语录', max_length=255, verbose_name='语录内容'),
        ),
    ]
