# Generated by Django 2.2.1 on 2021-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveword', '0023_auto_20210217_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='category',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='content',
            field=models.CharField(default='社会经典语录', max_length=255, verbose_name='文本内容'),
        ),
    ]
